namespace throw_error

fn main() {
    2 + "test"
}